on:
  workflow_dispatch:
  
jobs:
   win_build:
     runs-on: windows-latest
     name: windows build
     steps:           
       - name: Install Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.11'
       
       - name: Check Vars
         run: |
            dir
            git clone https://github.com/filispeen/goo-engine-compiled --depth 1
            dir
